version: "2"
services:
  build_node:
    profiles: ["build"]
    image: "rust:1.57"
    volumes:
      - ./distributed_nodes:/distributed_nodes
    environment:
      - USER=root

  node1:
    image: "distributed_node"
    hostname: node1
    ports:
      - "6379:6379"
    #depends_on:
    #  - "node2"
    environment:
      - NODES=node2:6380
      - BIND=0.0.0.0:6379
    networks:
      main:
        aliases:
          - node1

  node2:
    image: "distributed_node"
    hostname: node2
    ports:
      - "6380:6379"
    environment:
      - NODES=node1:6379
      - BIND=0.0.0.0:6380
    networks:
      main:
        aliases:
          - node2

networks:
  main: